spring:
  application:
    name: backend-api
  profiles:
    active: dev

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test-db
    username: sa
    password:
    driverClassName: org.h2.Driver
